<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PaintingsPage.aspx.cs" Inherits="SimionMariaBDIProiectTablou.PaintingsPage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style3 {
            width: 64%;
        }
        .auto-style6 {
            height: 26px;
        }
        .auto-style8 {
            height: 26px;
            width: 130px;
        }
        .auto-style9 {
            width: 35px;
            height: 26px;
        }
        .auto-style11 {
            height: 26px;
            width: 158px;
        }
        .auto-style12 {
            height: 26px;
            width: 208px;
        }
        .auto-style13 {
            height: 26px;
            width: 123px;
        }
        .auto-style14 {
            width: 61px;
            height: 26px;
        }
        .auto-style15 {
            width: 74px;
            height: 26px;
        }
        .auto-style16 {
            width: 488px;
        }
        .auto-style17 {
            width: 583px;
        }
        .auto-style18 {
            width: 858px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <asp:SqlDataSource ID="SqlDataSource_Painting" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT [IdLucrare], [Title], [Artist], [Year], [Technique], [ValoareMinima], [Dimensions], [Disponibilitate] FROM [Paintings]"></asp:SqlDataSource>
        <table class="auto-style3" border="1">
            <tr>
                <td class="auto-style14">
                    <asp:Label ID="LabelIDLucrare" runat="server" Text="ID"></asp:Label>
                </td>
                <td class="auto-style11">
                    <asp:Label ID="LabelTitle" runat="server" Text="Title"></asp:Label>
                </td>
                <td class="auto-style8">
                    <asp:Label ID="LabelArtist" runat="server" Text="Artist"></asp:Label>
                </td>
                <td class="auto-style9">
                    <asp:Label ID="LabelYear" runat="server" Text="Year"></asp:Label>
                </td>
                <td class="auto-style12">
                    <asp:Label ID="LabelTechique" runat="server" Text="Technique"></asp:Label>
                </td>
                <td class="auto-style6">
                    <asp:Label ID="LabelDimensions" runat="server" Text="Dimensions"></asp:Label>
                </td>
                <td class="auto-style13">
                    <asp:Label ID="LabelMinValue" runat="server" Text="MinValue"></asp:Label>
                </td>
                <td class="auto-style15">
                    <asp:Label ID="LabelDisponibilitate" runat="server" Text="LabelAvailability"></asp:Label>
                </td>
            </tr>
            
           
        </table>
        <table style="width:100%;">
            <tr>
                <td class="auto-style18">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" CellSpacing="1" DataKeyNames="IdLucrare" DataSourceID="SqlDataSource_Painting" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" ShowFooter="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="IdLucrare" HeaderText="IdLucrare" InsertVisible="False" ReadOnly="True" SortExpression="IdLucrare" />
                <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                <asp:BoundField DataField="Artist" HeaderText="Artist" SortExpression="Artist" />
                <asp:BoundField DataField="Year" HeaderText="Year" SortExpression="Year" />
                <asp:BoundField DataField="Technique" HeaderText="Technique" SortExpression="Technique" />
                <asp:BoundField DataField="Dimensions" HeaderText="Dimensions" SortExpression="Dimensions" />
                <asp:BoundField DataField="ValoareMinima" HeaderText="ValoareMinima" SortExpression="ValoareMinima" />
                <asp:BoundField DataField="Disponibilitate" HeaderText="Disponibilitate" SortExpression="Disponibilitate" />
            </Columns>
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" Font-Bold="true" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
                </td>
                <td>
                    <asp:Image ID="ImageSelectedPainting" runat="server" Height="390px" Width="596px" />
                </td>
        
            </tr>
            
        </table>
        <asp:RadioButton ID="RadioButtonAll" runat="server" AutoPostBack="True" GroupName="Availability" Checked="True" Text="All" OnCheckedChanged="RadioButtonAll_CheckedChanged" />
        <asp:RadioButton ID="RadioButtonUnavailable" runat="server" AutoPostBack="True" GroupName="Availability" Text="Unavailable" OnCheckedChanged="RadioButtonUnavailable_CheckedChanged" />
        <asp:RadioButton ID="RadioButtonAvailable" runat="server" AutoPostBack="True" GroupName="Availability" OnCheckedChanged="RadioButtonAvailable_CheckedChanged" Text="Available" />
        <div>
            <table style="width:100%;">
                <tr>
                    <td class="auto-style16">
                        <asp:Label ID="LabelFiltrareDupaTehnica" runat="server" Font-Bold="True" Font-Overline="True" Font-Size="Large" Text="Filter by techinque"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style16">
                        <asp:CheckBox ID="CheckBoxOil" runat="server" AutoPostBack="True" OnCheckedChanged="CheckBoxOil_CheckedChanged" Text="Oil on canvas" />
                    </td>
                    <td class="auto-style17">
                        <asp:CheckBox ID="CheckBoxTempera" runat="server" AutoPostBack="True" OnCheckedChanged="CheckBoxTempera_CheckedChanged" Text="Tempera on wood" />
                    </td>
                    <td>
                        <asp:CheckBox ID="CheckBoxPastel" runat="server" AutoPostBack="True" OnCheckedChanged="CheckBoxPastel_CheckedChanged" Text="Pastel on cardboard" />
                    </td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
